use INCLASS;

DESC EMPLOYEE;
SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE ADD(JOB VARCHAR(20), GENDER VARCHAR(2));

ALTER TABLE EMPLOYEE DROP EMAIL;

ALTER TABLE EMPLOYEE DROP JOB, DROP GENDER;

ALTER TABLE EMPLOYEE MODIFY F_NAME VARCHAR(10);

ALTER TABLE EMPLOYEE MODIFY F_NAME VARCHAR(3); /* ERROR: Existing data violates given condition */