use inclass;
SELECT * FROM COUNTRY;

# Q1
SELECT C_NAME FROM COUNTRY WHERE LENGTH(C_NAME)>8;

# Q2
SELECT FLOOR(REVENUE) FROM COUNTRY;

# Q3
SELECT UPPER(C_NAME) FROM COUNTRY;

# Q4
SELECT COUNTRY_ID,C_NAME,REGION_ID,REVENUE FROM COUNTRY WHERE C_NAME LIKE '%D_';

# Q5
SELECT COUNTRY_ID,C_NAME,REVENUE FROM COUNTRY ORDER BY REVENUE DESC LIMIT 2,2;

# Q6
select * from country group by region_id;

select * from product;
# Q7
SELECT PNAME,PRICE FROM PRODUCT WHERE PNAME LIKE 'PENCIL%';

SELECT PNAME,PRICE FROM PRODUCT WHERE PNAME LIKE 'P__ %';

SELECT * FROM PRODUCT WHERE (PRICE BETWEEN 1.0 AND 2.0) AND (QUANTITY BETWEEN 1000 AND 2000);

SELECT PRICE, CONCAT(PROD_CODE, ' - ', PNAME) "PRODUCT DESCRIPTION" FROM PRODUCT;

SELECT MAX(PRICE) - MIN(PRICE) "DIFF" FROM PRODUCT;
